name: Release and publish packages

on:
  push:
    branches:
      - main
    paths:
      - package.json

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  check-version-change:
    outputs:
      changed: ${{ steps.check-version.outputs.result }}

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Check if version has changed
        id: check-version
        uses: actions/github-script@v6
        with:
          script: |
            const version = '${{ inputs.version }}' || require('./lerna.json').version;
            // Find a release for that version
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: `release-v${version}`,
            }).catch(() => null);

            // If the release exists, the version has not changed
            if (release) {
              console.log(`Version ${version} has an existing release`);
              console.log(release.data.html_url);
              core.summary.addLink(`Release v${version}`, release.data.html_url);
              await core.summary.write();
              return "false";
            }
            console.log(`Version ${version} does not have a release`);
            return true;

  release:
    environment: publish

    needs: check-version-change
    if: ${{ needs.check-version-change.outputs.changed == 'true' }}

    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      PKG_VERSION: "" # will be set in the workflow

    outputs:
      version: ${{ env.PKG_VERSION }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"

      - name: Parse version from package.json
        run: |
          echo "PKG_VERSION=$(node -p -e "require('./lerna.json').version")" >> $GITHUB_ENV

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs");

            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "release-v${{ env.PKG_VERSION }}",
              name: "v${{ env.PKG_VERSION }}",
              draft: false,
              prerelease: false
            });

            core.summary.addLink(`Release v${{ env.PKG_VERSION }}`, release.data.html_url);
            await core.summary.write();

      - name: Publish packages
        run: |
          lerna publish from-git
